
import React, { useState } from 'react';
import { StockAnalysis } from '../types';
import OrderBook from './OrderBook';
import { 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer,
  AreaChart,
  Area
} from 'recharts';

interface AnalysisViewProps {
  data: StockAnalysis;
}

const AnalysisView: React.FC<AnalysisViewProps> = ({ data }) => {
  const [copied, setCopied] = useState(false);
  const numericPrice = parseFloat(data.currentPrice.replace(/[^0-9.]/g, '')) || 0;

  const handleShare = async () => {
    const shareUrl = `${window.location.origin}${window.location.pathname}?symbol=${data.symbol}`;
    if (navigator.share) {
      await navigator.share({ title: data.companyName, url: shareUrl });
    } else {
      await navigator.clipboard.writeText(shareUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadReport = () => {
    const reportContent = `
BHARATSTOCK AI - FINANCIAL ANALYSIS REPORT
Generated on: ${new Date().toLocaleString()}
--------------------------------------------------

COMPANY SUMMARY
Name: ${data.companyName}
Symbol: ${data.symbol}
Current Market Price: ₹${data.currentPrice}
Risk Profile: ${data.riskScore}

AI FORECAST
Target Price: ₹${data.prediction.targetPrice}
Expected Return: ${data.prediction.expectedReturn}
Timeframe: ${data.prediction.timeframe}

TECHNICAL SCORECARD
Quality: ${data.technicalScorecard.quality}/100
Valuation: ${data.technicalScorecard.valuation}/100
Momentum: ${data.technicalScorecard.momentum}/100

GROWTH DRIVERS (PROS)
${data.pros.map(pro => `- ${pro}`).join('\n')}

CRITICAL RISKS (CONS)
${data.cons.map(con => `- ${con}`).join('\n')}

STRATEGIC ANALYSIS
${data.detailedAnalysis}

SECTOR PEERS
${data.peers.map(p => `${p.symbol} (${p.companyName}): ₹${p.price}`).join('\n')}

--------------------------------------------------
DISCLAIMER: This report is generated by AI for informational purposes only.
BharatStock AI is not a SEBI registered advisor.
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${data.symbol}_Analysis_Report.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const sentimentWeight = (data.pros.length / (data.pros.length + data.cons.length)) * 100;

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-700">
      {/* Header & Risk Alert */}
      <div className="space-y-4">
        {data.riskScore === 'High' && (
          <div className="bg-rose-500/10 border border-rose-500/30 p-3 rounded-xl flex items-center gap-3 animate-pulse">
            <svg className="w-5 h-5 text-rose-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
            <p className="text-[10px] font-black uppercase tracking-widest text-rose-400">High Volatility Warning: AI detects significant downside risk factors.</p>
          </div>
        )}

        <div className="bg-[#111827] p-6 rounded-2xl border border-slate-800 backdrop-blur-sm flex flex-col md:flex-row justify-between items-start md:items-center gap-4 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/5 rounded-full blur-3xl -mr-16 -mt-16"></div>
          <div className="z-10">
            <div className="flex items-center gap-3">
              <h2 className="text-3xl font-extrabold text-white">{data.symbol}</h2>
              <span className={`px-3 py-1 rounded-lg text-[9px] font-black uppercase tracking-widest border ${
                data.riskScore === 'Low' ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' :
                data.riskScore === 'Medium' ? 'bg-amber-500/10 text-amber-400 border-amber-500/20' :
                'bg-rose-500/10 text-rose-400 border-rose-500/20'
              }`}>
                {data.riskScore} Risk
              </span>
            </div>
            <p className="text-slate-400 mt-1 font-medium">{data.companyName}</p>
            <div className="flex gap-4 mt-3">
              <button onClick={handleShare} className="text-[10px] font-bold text-slate-500 hover:text-white flex items-center gap-2 uppercase tracking-widest transition-colors">
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" /></svg>
                {copied ? 'Link Copied' : 'Share Intel'}
              </button>
              <button onClick={handleDownloadReport} className="text-[10px] font-bold text-indigo-400 hover:text-indigo-300 flex items-center gap-2 uppercase tracking-widest transition-colors">
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                Download Report
              </button>
            </div>
          </div>
          <div className="text-right z-10">
            <p className="text-[10px] text-slate-500 uppercase tracking-widest font-black mb-1">CMP (Live Grounded)</p>
            <p className="text-4xl font-black text-white tracking-tighter">₹{numericPrice.toLocaleString('en-IN')}</p>
          </div>
        </div>
      </div>

      {/* Main Analysis Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left Column: Visuals & Forecast */}
        <div className="lg:col-span-1 space-y-6">
          {/* Performance Chart */}
          <div className="bg-[#111827] p-4 rounded-2xl border border-slate-800 h-64">
            <h4 className="text-[9px] font-black text-slate-500 uppercase tracking-widest mb-4">30D Price Action (AI Simulated)</h4>
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={data.priceHistory}>
                <defs>
                  <linearGradient id="colorPrice" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#6366f1" stopOpacity={0.3}/>
                    <stop offset="95%" stopColor="#6366f1" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
                <XAxis dataKey="date" hide />
                <YAxis hide domain={['auto', 'auto']} />
                <Tooltip 
                  contentStyle={{ backgroundColor: '#111827', border: '1px solid #334155', borderRadius: '8px', fontSize: '10px' }}
                  itemStyle={{ color: '#fff' }}
                  labelStyle={{ display: 'none' }}
                />
                <Area type="monotone" dataKey="price" stroke="#6366f1" strokeWidth={2} fillOpacity={1} fill="url(#colorPrice)" />
              </AreaChart>
            </ResponsiveContainer>
          </div>

          {/* Target Card */}
          <div className="bg-gradient-to-br from-indigo-600 to-indigo-900 p-6 rounded-2xl shadow-xl text-white relative overflow-hidden">
            <div className="absolute -bottom-4 -right-4 w-24 h-24 bg-white/10 rounded-full blur-2xl"></div>
            <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
              AI Target
            </h3>
            <div className="space-y-4">
              <div>
                <p className="text-indigo-100 text-[10px] uppercase font-black opacity-70">Projected Goal</p>
                <p className="text-3xl font-black tracking-tighter">₹{data.prediction.targetPrice}</p>
              </div>
              <div className="flex justify-between items-end">
                <div>
                  <p className="text-indigo-100 text-[10px] uppercase font-black opacity-70">Upside</p>
                  <p className="text-xl font-black text-emerald-300">+{data.prediction.expectedReturn}</p>
                </div>
                <div className="text-right">
                  <p className="text-indigo-100 text-[10px] uppercase font-black opacity-70">Horizon</p>
                  <p className="text-sm font-bold">{data.prediction.timeframe}</p>
                </div>
              </div>
            </div>
          </div>

          <OrderBook currentPrice={numericPrice} sentiment={data.orderBookInsight.sentiment} />
        </div>

        {/* Center/Right Column: Pros, Cons, and Details */}
        <div className="lg:col-span-2 space-y-6">
          {/* Sentiment Summary Meter */}
          <div className="bg-[#111827] p-5 rounded-2xl border border-slate-800">
            <div className="flex justify-between items-center mb-2">
              <span className="text-[10px] font-black uppercase tracking-widest text-slate-500">Analyst Sentiment Weight</span>
              <span className="text-xs font-bold text-white">{sentimentWeight.toFixed(0)}% Bullish</span>
            </div>
            <div className="w-full h-2 bg-slate-800 rounded-full flex overflow-hidden">
              <div className="h-full bg-emerald-500 transition-all duration-1000" style={{ width: `${sentimentWeight}%` }}></div>
              <div className="h-full bg-rose-500 transition-all duration-1000" style={{ width: `${100 - sentimentWeight}%` }}></div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-[#111827] p-6 rounded-2xl border border-slate-800 border-l-4 border-l-emerald-500/50">
              <h4 className="text-emerald-400 font-black mb-4 text-[10px] uppercase tracking-widest flex items-center gap-2">
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 10l7-7m0 0l7 7m-7-7v18" /></svg>
                Growth Drivers (Pros)
              </h4>
              <ul className="space-y-4">
                {data.pros.map((pro, i) => (
                  <li key={i} className="text-xs text-slate-300 flex gap-3 leading-relaxed">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 shrink-0 mt-1.5"></span> {pro}
                  </li>
                ))}
              </ul>
            </div>
            <div className="bg-[#111827] p-6 rounded-2xl border border-slate-800 border-l-4 border-l-rose-500/50">
              <h4 className="text-rose-400 font-black mb-4 text-[10px] uppercase tracking-widest flex items-center gap-2">
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 14l-7 7m0 0l-7-7m7 7V3" /></svg>
                Risk Factors (Cons)
              </h4>
              <ul className="space-y-4">
                {data.cons.map((con, i) => (
                  <li key={i} className="text-xs text-slate-300 flex gap-3 leading-relaxed">
                    <span className="w-1.5 h-1.5 rounded-full bg-rose-500 shrink-0 mt-1.5"></span> {con}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <div className="bg-[#111827] p-6 rounded-2xl border border-slate-800">
            <h4 className="text-[10px] font-black text-slate-500 uppercase tracking-widest mb-4">Competitor Benchmark</h4>
            <div className="overflow-x-auto">
              <table className="w-full text-left">
                <thead>
                  <tr className="border-b border-slate-800 text-[9px] text-slate-600 uppercase">
                    <th className="pb-3">Symbol</th>
                    <th className="pb-3 text-right">Price</th>
                    <th className="pb-3 text-right">M.Cap</th>
                  </tr>
                </thead>
                <tbody className="text-[11px] text-slate-300">
                  {data.peers.map((peer, i) => (
                    <tr key={i} className="border-b border-slate-800/50 hover:bg-white/5 transition-colors">
                      <td className="py-3">
                        <div className="font-bold text-white">{peer.symbol}</div>
                        <div className="text-[9px] text-slate-600">{peer.companyName}</div>
                      </td>
                      <td className="py-3 text-right font-bold text-indigo-400">₹{peer.price}</td>
                      <td className="py-3 text-right text-slate-500 font-mono">{peer.marketCap}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <div className="bg-[#111827] p-8 rounded-2xl border border-slate-800 relative">
            <div className="absolute top-0 right-0 p-4 opacity-10">
              <svg className="w-20 h-20 text-indigo-500" fill="currentColor" viewBox="0 0 24 24"><path d="M14.017 21L14.017 18C14.017 16.8954 13.1216 16 12.017 16H8.01703V12H12.017C14.2261 12 16.017 10.2091 16.017 8C16.017 5.79086 14.2261 4 12.017 4C9.80789 4 8.01703 5.79086 8.01703 8V10H4.01703V8C4.01703 3.58172 7.59875 0 12.017 0C16.4353 0 20.017 3.58172 20.017 8C20.017 11.4224 17.8643 14.3422 14.8357 15.4411C14.9525 15.6171 15.017 15.801 15.017 16V21H14.017Z" /></svg>
            </div>
            <h4 className="text-white font-black mb-4 uppercase tracking-widest text-[10px]">AI Strategic Intelligence</h4>
            <p className="text-slate-300 leading-relaxed text-sm whitespace-pre-line relative z-10">{data.detailedAnalysis}</p>
          </div>

          {data.sources.length > 0 && (
            <div className="flex flex-wrap gap-2">
              {data.sources.map((s, i) => (
                <a key={i} href={s.uri} target="_blank" rel="noopener noreferrer" className="text-[9px] bg-slate-900 hover:bg-slate-800 text-slate-500 hover:text-indigo-400 px-3 py-2 rounded-lg border border-slate-800 transition-all uppercase tracking-widest font-black">
                  {s.title}
                </a>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AnalysisView;
